added UserController
entertainment-veks/spring pull request #3
Opened 2021-02-11 13:34 UTC by entertainment-veks

added findByUser in UserDao and UserService
added config files

2021-02-11 13:50 UTC, Fedich09 requested changes

2021-02-11 13:50 UTC, Fedich09 commented on pom.xml
> +        </dependency>
```suggestion

```

2021-02-11 13:50 UTC, Fedich09 commented on src/main/java/spring/intro/controller/UserController.java
> +
```suggestion
```

2021-02-11 15:02 UTC, Fedich09 approved these changes

2021-02-11 17:26 UTC, dmytro-hryhoruk requested changes

2021-02-11 17:26 UTC, dmytro-hryhoruk commented on sample/servlet/container/deploy/directory/META-INF/MANIFEST.MF
> +Manifest-Version: 1.0
?

2021-02-11 17:26 UTC, dmytro-hryhoruk commented on src/main/java/spring/intro/controller/UserController.java
> +@ComponentScan(basePackages = {"spring.intro.controller"})
it's not a configuration bean

2021-02-11 17:26 UTC, dmytro-hryhoruk commented on src/main/java/spring/intro/dto/UserResponseDto.java
> +
```suggestion
```

2021-02-12 08:14 UTC, dmytro-hryhoruk approved these changes

2021-02-12 08:14 UTC, dmytro-hryhoruk commented on pom.xml
> +        </dependency>
please remove this dependency

2021-02-12 08:14 UTC, dmytro-hryhoruk commented on pom.xml
> +        </dependency>
this too

2021-02-12 08:31 UTC, merged